config/routes.rb
Rails.application.routes.draw do 

   
 # resources :registrations

  root "events#index"
  
  resources :events do
    resources :registrations
  end

  resource :session, only: [:new, :create, :destroy]

  resources :users
  get "signup" => "users#new"
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

	has_many :registrations, dependent: :destroy

	validates :name, :description, :location, presence: true

	validates :description, length: { minimum: 25 }

	validates :price, numericality: { greater_than_or_equal_to: 0 }

	validates :capacity, numericality:
	                      {only_integer: true, greater_than: 0} 

	validates :image_file_name, format: {  
	  with: /\w+\.(jpg|png)\z/i,
	  message: "must be a JPG or PNG image"
	}

  def self.upcoming
	where("starts_at > ?", Time.now).order("starts_at")
  end

  def free?
		price.blank? || price.zero?
	end

	def sold_out?
		(capacity - registrations.size).zero?
  end

end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :event
  belongs_to :user

  #validates :name, presence: true

  #validates :email, format: { with: /\S+@\S+/ }

  HOW_HEARD_OPTIONS = [
    'News latter',
    'Blog post',
    'Twitter',
    'Web search',
    'Friend/Coworker',
    'other'
  ]

  validates :how_heard,
            inclusion: { in: HOW_HEARD_OPTIONS }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :registrations, dependent: :destroy

  has_one_attached :person

  has_secure_password

  validates :name, presence: true

  validates :email, format: { with: /\S+@\S+/ },
                    uniqueness: { case_sensitive: false }
                    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

private

	def current_user
		User.find(session[:user_id]) if session[:user_id]
	end

	helper_method :current_user

	def current_user?(user)
		current_user == user
	end

	helper_method :current_user?

	def current_user_admin?
		current_user && current_user.admin?
	end

	helper_method :current_user_admin?

	def require_signin
		unless current_user
		  session[:intendened_url] = request.url
          redirect_to new_session_url, alert: "Please sign in first!"
		end
	end

	def require_admin
		unless current_user_admin?
			redirect_to events_url, alert: "Unauthorized access!"
		end
	end



	
end

app/controllers/events_controller.rb
  class EventsController < ApplicationController

	before_action :require_signin, except: [:index, :show]
	before_action :require_admin, except: [:index, :show]

    def index
    @events = Event.upcoming 
    end


	def show
	  @event = Event.find(params[:id])
	end

	def edit
	  @event = Event.find(params[:id])
	end

  def update
	@event = Event.find(params[:id])
	  if @event.update(event_params)
	    redirect_to @event, notice: "Event succesfully updated!"
		else
			render :edit	
	 end
	end

  def new
    @event = Event.new
  end

  def create
    @event= Event.new(event_params)
    if @event.save
			redirect_to @event, notice: "Event succesfully created!"
		else
			render :new
		end 
  end

  def destroy
		@event = Event.find(params[:id])
		@event.destroy
		redirect_to events_url
  end


  private

    def event_params  
      params.require(:event).
        permit(:name, :description, :location, :price, :starts_at,
             :capacity, :image_file_name)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :require_signin
	before_action :set_event

  def index
    @registrations = @event.registrations
  end

  def new
    @registration = @event.registrations.new
  end

  def create
    @registration = @event.registrations.new(registration_params)
    @registration.user = current_user

    if @registration.save
      redirect_to event_registrations_url(@event),
        notice: "Thanks for registering!"
    else
      render :new
    end
  end

private

  def registration_params
    params.require(:registration).permit(:how_heard)
  end

  def set_event
    @event = Event.find(params[:event_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new

    end

    def create
			user = User.find_by(email: params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to (session[:intendened_url] || user), 
                    notice: "Welcome back, #{user.name}!"
        session[:intendened_url] = nil            
      else
        flash.now[:alert] = "Invalid email/password combination!"
        render :new
      end
    end
        

    def destroy
      session[:user_id] = nil
      redirect_to events_url, notice: "You're now signed out!"
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :require_signin, except: [:new, :create]
	before_action :require_correct_user, only: [:edit, :update, :destroy]

	def index
		@users = User.all
  end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	  end
	
	def create
	  @user = User.new(user_params)

	  if @user.save
			UserMailer.with(user: @user).welcome_email.deliver_later
			session[:user_id] = @user.id
		  redirect_to @user, notice: "Thanks for signing up!"
		else
		   render :new
		end
	end

	def edit
	end

	def update
	  if @user.update(user_params)
		   redirect_to @user, notice: "Account succesfully updated!"
		 else
		   render :edit
		end
	end

	def destroy
		@user.destroy
		redirect_to events_url, alert: "Account succesfully deleted"
		session[:user_id] = nil
	end


private

  def require_correct_user
	@user = User.find(params[:id])
	  redirect_to events_url unless current_user?(@user)
  end
	
  def user_params
	params.require(:user).
	 permit(:name, :email, :password, :password_confirmation, :person)
  end
	
	
	
	
end
	

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/events_helper.rb
module EventsHelper
  
	def price(event)
		if event.price == 0
			"Free"
		else
			number_to_currency(event.price, precition: 0) 
		end
	end

	def day_and_time(event)
		event.starts_at.strftime("%B %d at %I:%M %p")
	end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
	
	def register_or_sold_out(event)
    if event.sold_out?
      content_tag(:span, "Sold Out!", class: "sold-out")
    else
      link_to "Register!", new_event_registration_path(event),
             class: "register"
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |f| %>

 <%= render "shared/errors", object: event %>

 <%= f.label :name %>
 <%= f.text_field :name, autofocus: true %>

 <%= f.label :description %>
 <%= f.text_area :description, rows: 5 %>

 <%= f.label :location %>
 <%= f.text_field :location %>

 <%= f.label :price %>
 <%= f.number_field :price %>

 <%= f.label :starts_at %>
 <%= f.datetime_select :starts_at, {ampm: true}, {class: "datetime"} %>

 <%= f.label :capacity %>
 <%= f.number_field :capacity %>

 <%= f.label :image_file_name %>
 <%= f.text_field :image_file_name %>



 <%= f.submit %>
 <% end %>

app/views/events/edit.html.erb
<h1> Editing <%= @event.name %></h1> 

<%= render "form", event: @event%>

app/views/events/index.html.erb
 <% @events.each do |event| %>
   <section class="event">
     <div class="image">
	   <%= image_tag event.image_file_name %>
	 </div>
	   <div class="summary">
		   <h2><%= link_to event.name, event %></h2>
	     <h3><%=  day_and_time(event) %> in <%= event.location %></h3>
			 <span class = "price">
         <%= price(event)%>
			 </span>
  
      <p>
        <%= truncate(event.description, length: 35, seprator: ' ') %>
      </p>
		 </div>
		</section>
	<% end %>

  <% if current_user_admin? %>
	  <section class="admin">
       <%= link_to "Add new event", new_event_path, class: "button" %>
    </section>
	<% end %>

  

 
   

app/views/events/new.html.erb
<h1>Create a New Event</h1>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<section class="event-details">
  <div class="image">
	  <%= image_tag @event.image_file_name %>
  </div>
	<div class="details">
    <h1><%= @event.name %></h1>
	  <h2> 
       <%= pluralize(@event.capacity, "spot") %> &bull; <%= price(@event)  %>
    </h2>
	  <h3>
      <%= day_and_time(@event) %> in <%= @event.location %>
    </h3>
			<p>
         <%= @event.description %>
      </p>

      <div class="register">
        <%= register_or_sold_out(@event) %>
      <p>
        <%= link_to "who's registered?", event_registrations_path(@event) %>
      </p>
    </div>

    </div>
  </section>

  <% if current_user_admin? %>
    <section class="admin">
      <%= link_to "edit", edit_event_path(@event), class: "button" %>
      <%= link_to "delete", @event, class: "button", method: :delete,
                                           data: { confirm: "Are you sure?!" } %>                       

    </section>
  <% end %>

        

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="flash notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="flash alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
      <p>
        Made in <a href="https://pragmaticstudio.com">The pragmatic studio</a>
      </p>
    </footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to image_tag("logo"), root_path %>
    <ul class="left">
      <li>
        <%= link_to "All events", events_path %>
      </li>
    </ul>
    <ul class="right">
      <% if current_user %>
        <li>
          <%= link_to current_user.name, current_user %>
        </li> 
        <li>
          <%= link_to "Sign out", session_path,
                      method: :delete, class: "button" %>
        </li>              
       <% else %>
       <li>
        <%= link_to "Sign In", new_session_path, class: "button" %>
       </li> 
       <li>
         <%= link_to "Sign Up", signup_path, class: "button" %>
       </li>
     <% end %>
    </ul>  
  </nav>
</header> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "layouts/header" %>

    
    <div class= "content">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>

  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section class="errors"%>
    <h2> 
		  oops! your form could not be saved.
		</h2>
		<h3>
		  please correct the following
			<%= pluralize(object.errors.size, "error") %>:
		</h3>
		<ul>
		<% object.errors.full_messages.each do |message| %>
		  <li><%= message %></li>
		 <% end %>
		</ul>
	</section>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <%= render "shared/errors", object: user %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirm Password" %>
  <%= f.password_field :password_confirmation %>

  <%= f.label :person %>
  <%= f.file_field :person %>

  <% if user.new_record? %>
    <%= f.submit "Create Account" %>
  <% else %>  
    <%= f.submit "Update Account" %>
  <% end %>

<% end %>

app/views/users/edit.html.erb
<h1>Edit Account</h1>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1> <%= pluralize(@users.size, "User") %></h1>
<ul class="users">
  <% @users.each do |user| %>
	  <li> 
      <%= link_to user.name, user %>
			created
      <%= time_ago_in_words(user.created_at) %> ago 
		</li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<section class="user">
  <h1><%= @user.name %></h1>
  <h2><%= mail_to(@user.email) %></h2>
  <p>
    <strong>Person:</strong>
    <% if @user.person.attached? %>
      <%= image_tag @user.person, width: "200px" %>
    <% end %>
  </p>
  <% if current_user?(@user) %>
  <div class="actions">
    <%= link_to "Edit Account", edit_user_path(@user),
                     class: "button edit" %>

    <%= link_to "Delete Account", @user, method: :delete,
                data: { confirm: 'Are you sure?'},
                class: "button delete" %>
   </div>
  <% end %>
</section>